/**
 * @(#)ObjectFactory.java
 * Copyright (c) 2013, Province of British Columbia.
 * All rights reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.29 at 03:35:56 PM PDT 
//


package ca.bc.gov.open.pssg.ecrc.rest.checkApplicantForPrevCRC;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.bc.gov.ag.vcrc.rest.checkApplicantForPrevCRC package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 * @author Ministry of Attorney General
 * @author $LastChangedBy: smillar $
 * @version $Revision: 106022 $, ($LastChangedDate: 2014-03-31 15:09:52 -0700 (Mon, 31 Mar 2014) $)
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.bc.gov.ag.vcrc.rest.checkApplicantForPrevCRC
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckApplicantForPrevCRC }
     * 
     */
    public CheckApplicantForPrevCRC createCheckApplicantForPrevCRC() {
        return new CheckApplicantForPrevCRC();
    }

}
