//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.27 at 02:19:50 PM PDT 
//


package ca.bc.gov.ag.ecrc.rest.initialRequest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.bc.gov.ag.equifaxservice.rest.server.types.initialrequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.bc.gov.ag.equifaxservice.rest.server.types.initialrequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InitialRequest }
     * 
     */
    public InitialRequest createInitialRequest() {
        return new InitialRequest();
    }

    /**
     * Create an instance of {@link InitialRequest.Identity }
     * 
     */
    public InitialRequest.Identity createInitialRequestIdentity() {
        return new InitialRequest.Identity();
    }

    /**
     * Create an instance of {@link InitialRequest.Client }
     * 
     */
    public InitialRequest.Client createInitialRequestClient() {
        return new InitialRequest.Client();
    }

    /**
     * Create an instance of {@link InitialRequest.Identity.Name }
     * 
     */
    public InitialRequest.Identity.Name createInitialRequestIdentityName() {
        return new InitialRequest.Identity.Name();
    }

    /**
     * Create an instance of {@link InitialRequest.Identity.Address }
     * 
     */
    public InitialRequest.Identity.Address createInitialRequestIdentityAddress() {
        return new InitialRequest.Identity.Address();
    }

    /**
     * Create an instance of {@link InitialRequest.Identity.DriversLicense }
     * 
     */
    public InitialRequest.Identity.DriversLicense createInitialRequestIdentityDriversLicense() {
        return new InitialRequest.Identity.DriversLicense();
    }

    /**
     * Create an instance of {@link InitialRequest.Identity.PhoneNumber }
     * 
     */
    public InitialRequest.Identity.PhoneNumber createInitialRequestIdentityPhoneNumber() {
        return new InitialRequest.Identity.PhoneNumber();
    }

}
