//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 11:07:20 AM PDT 
//


package ca.bc.gov.open.pssg.ecrc.rest.resultResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="responseDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="responseCd" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="responseMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reasonCodes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reasonCodeDescriptions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="riskStrategyDecision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="interactiveScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseDesc",
    "responseCd",
    "responseMessage",
    "reasonCodes",
    "reasonCodeDescriptions",
    "riskStrategyDecision",
    "score",
    "interactiveScore"
})
@XmlRootElement(name = "ResultResponse")
public class ResultResponse {

    @XmlElement(required = true)
    protected String responseDesc;
    protected int responseCd;
    @XmlElement(required = true)
    protected String responseMessage;
    @XmlElement(required = true)
    protected String reasonCodes;
    @XmlElement(required = true)
    protected String reasonCodeDescriptions;
    @XmlElement(required = true)
    protected String riskStrategyDecision;
    protected int score;
    protected int interactiveScore;

    /**
     * Gets the value of the responseDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseDesc() {
        return responseDesc;
    }

    /**
     * Sets the value of the responseDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseDesc(String value) {
        this.responseDesc = value;
    }

    /**
     * Gets the value of the responseCd property.
     * 
     */
    public int getResponseCd() {
        return responseCd;
    }

    /**
     * Sets the value of the responseCd property.
     * 
     */
    public void setResponseCd(int value) {
        this.responseCd = value;
    }

    /**
     * Gets the value of the responseMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseMessage() {
        return responseMessage;
    }

    /**
     * Sets the value of the responseMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseMessage(String value) {
        this.responseMessage = value;
    }

    /**
     * Gets the value of the reasonCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCodes() {
        return reasonCodes;
    }

    /**
     * Sets the value of the reasonCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCodes(String value) {
        this.reasonCodes = value;
    }

    /**
     * Gets the value of the reasonCodeDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCodeDescriptions() {
        return reasonCodeDescriptions;
    }

    /**
     * Sets the value of the reasonCodeDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCodeDescriptions(String value) {
        this.reasonCodeDescriptions = value;
    }

    /**
     * Gets the value of the riskStrategyDecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiskStrategyDecision() {
        return riskStrategyDecision;
    }

    /**
     * Sets the value of the riskStrategyDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiskStrategyDecision(String value) {
        this.riskStrategyDecision = value;
    }

    /**
     * Gets the value of the score property.
     * 
     */
    public int getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     */
    public void setScore(int value) {
        this.score = value;
    }

    /**
     * Gets the value of the interactiveScore property.
     * 
     */
    public int getInteractiveScore() {
        return interactiveScore;
    }

    /**
     * Sets the value of the interactiveScore property.
     * 
     */
    public void setInteractiveScore(int value) {
        this.interactiveScore = value;
    }

}
