//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 02:45:19 PM PDT 
//


package ca.bc.gov.open.pssg.ecrc.rest.doAuthenticateUser;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccessCodeResponse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="org_party_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="org_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contact_surname_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contact_first_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="address_line_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="address_line_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="city_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="province_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="postal_code_txt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contact_phone_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contact_fax_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="org_applicant_relationship" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="default_schedule_type_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="default_crc_scope_level_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ticket_found_yn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="already_used_yn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="valid_date_range_yn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ScopeLevels">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ScopeLevel" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="crc_scope_level_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="crc_scope_level_dsc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ScheduleTypes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ScheduleType" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="crc_schedule_type_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="crc_schedule_type_dsc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accessCodeResponse",
    "scopeLevels",
    "scheduleTypes",
    "message",
    "responseCode"
})
@XmlRootElement(name = "DoAuthenticateUser")
public class DoAuthenticateUser implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4109282517135265131L;
	
	@XmlElement(name = "AccessCodeResponse", required = true)
    protected DoAuthenticateUser.AccessCodeResponse accessCodeResponse;
    @XmlElement(name = "ScopeLevels", required = true)
    protected DoAuthenticateUser.ScopeLevels scopeLevels;
    @XmlElement(name = "ScheduleTypes", required = true)
    protected DoAuthenticateUser.ScheduleTypes scheduleTypes;
    @XmlElement(name = "Message", required = true)
    protected String message;
    @XmlElement(name = "ResponseCode")
    protected int responseCode;

    /**
     * Gets the value of the accessCodeResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DoAuthenticateUser.AccessCodeResponse }
     *     
     */
    public DoAuthenticateUser.AccessCodeResponse getAccessCodeResponse() {
        return accessCodeResponse;
    }

    /**
     * Sets the value of the accessCodeResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoAuthenticateUser.AccessCodeResponse }
     *     
     */
    public void setAccessCodeResponse(DoAuthenticateUser.AccessCodeResponse value) {
        this.accessCodeResponse = value;
    }

    /**
     * Gets the value of the scopeLevels property.
     * 
     * @return
     *     possible object is
     *     {@link DoAuthenticateUser.ScopeLevels }
     *     
     */
    public DoAuthenticateUser.ScopeLevels getScopeLevels() {
        return scopeLevels;
    }

    /**
     * Sets the value of the scopeLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoAuthenticateUser.ScopeLevels }
     *     
     */
    public void setScopeLevels(DoAuthenticateUser.ScopeLevels value) {
        this.scopeLevels = value;
    }

    /**
     * Gets the value of the scheduleTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DoAuthenticateUser.ScheduleTypes }
     *     
     */
    public DoAuthenticateUser.ScheduleTypes getScheduleTypes() {
        return scheduleTypes;
    }

    /**
     * Sets the value of the scheduleTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoAuthenticateUser.ScheduleTypes }
     *     
     */
    public void setScheduleTypes(DoAuthenticateUser.ScheduleTypes value) {
        this.scheduleTypes = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     */
    public int getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     */
    public void setResponseCode(int value) {
        this.responseCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="org_party_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="org_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contact_surname_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contact_first_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="address_line_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="address_line_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="city_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="province_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="country_nm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="postal_code_txt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contact_phone_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contact_fax_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="org_applicant_relationship" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="default_schedule_type_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="default_crc_scope_level_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ticket_found_yn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="already_used_yn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="valid_date_range_yn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orgPartyId",
        "orgNm",
        "contactSurnameNm",
        "contactFirstNm",
        "addressLine1",
        "addressLine2",
        "cityNm",
        "provinceNm",
        "countryNm",
        "postalCodeTxt",
        "contactPhoneNo",
        "contactFaxNo",
        "orgApplicantRelationship",
        "defaultScheduleTypeCd",
        "defaultCrcScopeLevelCd",
        "ticketFoundYn",
        "alreadyUsedYn",
        "validDateRangeYn"
    })
    public static class AccessCodeResponse implements Serializable {

        /**
		 * 
		 */
		private static final long serialVersionUID = -5896494208996237890L;
		
		@XmlElement(name = "org_party_id")
        protected int orgPartyId;
        @XmlElement(name = "org_nm", required = true)
        protected String orgNm;
        @XmlElement(name = "contact_surname_nm", required = true)
        protected String contactSurnameNm;
        @XmlElement(name = "contact_first_nm", required = true)
        protected String contactFirstNm;
        @XmlElement(name = "address_line_1", required = true)
        protected String addressLine1;
        @XmlElement(name = "address_line_2", required = true)
        protected String addressLine2;
        @XmlElement(name = "city_nm", required = true)
        protected String cityNm;
        @XmlElement(name = "province_nm", required = true)
        protected String provinceNm;
        @XmlElement(name = "country_nm", required = true)
        protected String countryNm;
        @XmlElement(name = "postal_code_txt", required = true)
        protected String postalCodeTxt;
        @XmlElement(name = "contact_phone_no", required = true)
        protected String contactPhoneNo;
        @XmlElement(name = "contact_fax_no", required = true)
        protected String contactFaxNo;
        @XmlElement(name = "org_applicant_relationship", required = true)
        protected String orgApplicantRelationship;
        @XmlElement(name = "default_schedule_type_cd", required = true)
        protected String defaultScheduleTypeCd;
        @XmlElement(name = "default_crc_scope_level_cd", required = true)
        protected String defaultCrcScopeLevelCd;
        @XmlElement(name = "ticket_found_yn", required = true)
        protected String ticketFoundYn;
        @XmlElement(name = "already_used_yn", required = true)
        protected String alreadyUsedYn;
        @XmlElement(name = "valid_date_range_yn", required = true)
        protected String validDateRangeYn;

        /**
         * Gets the value of the orgPartyId property.
         * 
         */
        public int getOrgPartyId() {
            return orgPartyId;
        }

        /**
         * Sets the value of the orgPartyId property.
         * 
         */
        public void setOrgPartyId(int value) {
            this.orgPartyId = value;
        }

        /**
         * Gets the value of the orgNm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrgNm() {
            return orgNm;
        }

        /**
         * Sets the value of the orgNm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrgNm(String value) {
            this.orgNm = value;
        }

        /**
         * Gets the value of the contactSurnameNm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactSurnameNm() {
            return contactSurnameNm;
        }

        /**
         * Sets the value of the contactSurnameNm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactSurnameNm(String value) {
            this.contactSurnameNm = value;
        }

        /**
         * Gets the value of the contactFirstNm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactFirstNm() {
            return contactFirstNm;
        }

        /**
         * Sets the value of the contactFirstNm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactFirstNm(String value) {
            this.contactFirstNm = value;
        }

        /**
         * Gets the value of the addressLine1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine1() {
            return addressLine1;
        }

        /**
         * Sets the value of the addressLine1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine1(String value) {
            this.addressLine1 = value;
        }

        /**
         * Gets the value of the addressLine2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressLine2() {
            return addressLine2;
        }

        /**
         * Sets the value of the addressLine2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressLine2(String value) {
            this.addressLine2 = value;
        }

        /**
         * Gets the value of the cityNm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCityNm() {
            return cityNm;
        }

        /**
         * Sets the value of the cityNm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCityNm(String value) {
            this.cityNm = value;
        }

        /**
         * Gets the value of the provinceNm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProvinceNm() {
            return provinceNm;
        }

        /**
         * Sets the value of the provinceNm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProvinceNm(String value) {
            this.provinceNm = value;
        }

        /**
         * Gets the value of the countryNm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryNm() {
            return countryNm;
        }

        /**
         * Sets the value of the countryNm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryNm(String value) {
            this.countryNm = value;
        }

        /**
         * Gets the value of the postalCodeTxt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPostalCodeTxt() {
            return postalCodeTxt;
        }

        /**
         * Sets the value of the postalCodeTxt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPostalCodeTxt(String value) {
            this.postalCodeTxt = value;
        }

        /**
         * Gets the value of the contactPhoneNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactPhoneNo() {
            return contactPhoneNo;
        }

        /**
         * Sets the value of the contactPhoneNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactPhoneNo(String value) {
            this.contactPhoneNo = value;
        }

        /**
         * Gets the value of the contactFaxNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactFaxNo() {
            return contactFaxNo;
        }

        /**
         * Sets the value of the contactFaxNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactFaxNo(String value) {
            this.contactFaxNo = value;
        }

        /**
         * Gets the value of the orgApplicantRelationship property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrgApplicantRelationship() {
            return orgApplicantRelationship;
        }

        /**
         * Sets the value of the orgApplicantRelationship property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrgApplicantRelationship(String value) {
            this.orgApplicantRelationship = value;
        }

        /**
         * Gets the value of the defaultScheduleTypeCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultScheduleTypeCd() {
            return defaultScheduleTypeCd;
        }

        /**
         * Sets the value of the defaultScheduleTypeCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultScheduleTypeCd(String value) {
            this.defaultScheduleTypeCd = value;
        }

        /**
         * Gets the value of the defaultCrcScopeLevelCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultCrcScopeLevelCd() {
            return defaultCrcScopeLevelCd;
        }

        /**
         * Sets the value of the defaultCrcScopeLevelCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultCrcScopeLevelCd(String value) {
            this.defaultCrcScopeLevelCd = value;
        }

        /**
         * Gets the value of the ticketFoundYn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTicketFoundYn() {
            return ticketFoundYn;
        }

        /**
         * Sets the value of the ticketFoundYn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTicketFoundYn(String value) {
            this.ticketFoundYn = value;
        }

        /**
         * Gets the value of the alreadyUsedYn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlreadyUsedYn() {
            return alreadyUsedYn;
        }

        /**
         * Sets the value of the alreadyUsedYn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlreadyUsedYn(String value) {
            this.alreadyUsedYn = value;
        }

        /**
         * Gets the value of the validDateRangeYn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValidDateRangeYn() {
            return validDateRangeYn;
        }

        /**
         * Sets the value of the validDateRangeYn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValidDateRangeYn(String value) {
            this.validDateRangeYn = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ScheduleType" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="crc_schedule_type_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="crc_schedule_type_dsc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scheduleType"
    })
    public static class ScheduleTypes implements Serializable {

        /**
		 * 
		 */
		private static final long serialVersionUID = 8785618542823101894L;
		
		@XmlElement(name = "ScheduleType")
        protected List<DoAuthenticateUser.ScheduleTypes.ScheduleType> scheduleType;

        /**
         * Gets the value of the scheduleType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the scheduleType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScheduleType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DoAuthenticateUser.ScheduleTypes.ScheduleType }
         * 
         * 
         */
        public List<DoAuthenticateUser.ScheduleTypes.ScheduleType> getScheduleType() {
            if (scheduleType == null) {
                scheduleType = new ArrayList<DoAuthenticateUser.ScheduleTypes.ScheduleType>();
            }
            return this.scheduleType;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="crc_schedule_type_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="crc_schedule_type_dsc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "crcScheduleTypeCd",
            "crcScheduleTypeDsc"
        })
        public static class ScheduleType implements Serializable {

            /**
			 * 
			 */
			private static final long serialVersionUID = -1903854598749177525L;
			
			@XmlElement(name = "crc_schedule_type_cd", required = true)
            protected String crcScheduleTypeCd;
            @XmlElement(name = "crc_schedule_type_dsc", required = true)
            protected String crcScheduleTypeDsc;

            /**
             * Gets the value of the crcScheduleTypeCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCrcScheduleTypeCd() {
                return crcScheduleTypeCd;
            }

            /**
             * Sets the value of the crcScheduleTypeCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCrcScheduleTypeCd(String value) {
                this.crcScheduleTypeCd = value;
            }

            /**
             * Gets the value of the crcScheduleTypeDsc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCrcScheduleTypeDsc() {
                return crcScheduleTypeDsc;
            }

            /**
             * Sets the value of the crcScheduleTypeDsc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCrcScheduleTypeDsc(String value) {
                this.crcScheduleTypeDsc = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ScopeLevel" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="crc_scope_level_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="crc_scope_level_dsc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scopeLevel"
    })
    public static class ScopeLevels implements Serializable {

        /**
		 * 
		 */
		private static final long serialVersionUID = 1226103178816712786L;
		
		@XmlElement(name = "ScopeLevel")
        protected List<DoAuthenticateUser.ScopeLevels.ScopeLevel> scopeLevel;

        /**
         * Gets the value of the scopeLevel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the scopeLevel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScopeLevel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DoAuthenticateUser.ScopeLevels.ScopeLevel }
         * 
         * 
         */
        public List<DoAuthenticateUser.ScopeLevels.ScopeLevel> getScopeLevel() {
            if (scopeLevel == null) {
                scopeLevel = new ArrayList<DoAuthenticateUser.ScopeLevels.ScopeLevel>();
            }
            return this.scopeLevel;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="crc_scope_level_cd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="crc_scope_level_dsc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "crcScopeLevelCd",
            "crcScopeLevelDsc"
        })
        public static class ScopeLevel implements Serializable {

            /**
			 * 
			 */
			private static final long serialVersionUID = 8214845860865026259L;
			
			@XmlElement(name = "crc_scope_level_cd", required = true)
            protected String crcScopeLevelCd;
            @XmlElement(name = "crc_scope_level_dsc", required = true)
            protected String crcScopeLevelDsc;

            /**
             * Gets the value of the crcScopeLevelCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCrcScopeLevelCd() {
                return crcScopeLevelCd;
            }

            /**
             * Sets the value of the crcScopeLevelCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCrcScopeLevelCd(String value) {
                this.crcScopeLevelCd = value;
            }

            /**
             * Gets the value of the crcScopeLevelDsc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCrcScopeLevelDsc() {
                return crcScopeLevelDsc;
            }

            /**
             * Sets the value of the crcScopeLevelDsc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCrcScopeLevelDsc(String value) {
                this.crcScopeLevelDsc = value;
            }

        }

    }

}
