//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 02:45:19 PM PDT 
//


package ca.bc.gov.open.pssg.ecrc.rest.doAuthenticateUser;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.bc.gov.ag.vcrc.rest.doAuthenticateUser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = -2297958046476456727L;

	/**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.bc.gov.ag.vcrc.rest.doAuthenticateUser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DoAuthenticateUser }
     * 
     */
    public DoAuthenticateUser createDoAuthenticateUser() {
        return new DoAuthenticateUser();
    }

    /**
     * Create an instance of {@link DoAuthenticateUser.ScheduleTypes.ScheduleType }
     * 
     */
    public DoAuthenticateUser.ScheduleTypes.ScheduleType createDoAuthenticateUserScheduleTypesScheduleType() {
        return new DoAuthenticateUser.ScheduleTypes.ScheduleType();
    }

    /**
     * Create an instance of {@link DoAuthenticateUser.ScheduleTypes }
     * 
     */
    public DoAuthenticateUser.ScheduleTypes createDoAuthenticateUserScheduleTypes() {
        return new DoAuthenticateUser.ScheduleTypes();
    }

    /**
     * Create an instance of {@link DoAuthenticateUser.AccessCodeResponse }
     * 
     */
    public DoAuthenticateUser.AccessCodeResponse createDoAuthenticateUserAccessCodeResponse() {
        return new DoAuthenticateUser.AccessCodeResponse();
    }

    /**
     * Create an instance of {@link DoAuthenticateUser.ScopeLevels }
     * 
     */
    public DoAuthenticateUser.ScopeLevels createDoAuthenticateUserScopeLevels() {
        return new DoAuthenticateUser.ScopeLevels();
    }

    /**
     * Create an instance of {@link DoAuthenticateUser.ScopeLevels.ScopeLevel }
     * 
     */
    public DoAuthenticateUser.ScopeLevels.ScopeLevel createDoAuthenticateUserScopeLevelsScopeLevel() {
        return new DoAuthenticateUser.ScopeLevels.ScopeLevel();
    }

}
